new: reusable workflows need to be top-level
Since this needs to do npm things, it might now work, but let's see...
Error: .github#L1
reusable workflows should be referenced at the top-level 'jobs.*.uses' key, not within steps